module.exports = {

    searchResults: [
        "Four Steps To The Epiphany Revised - James McEnroe",
        "Four Steps To The Epiphany - James McEnroe",
        "The Lean Start Up - Eric Reiss",
        "No Excuses - Brian Tracy",
        "Harry Potter and the Goblet of Fire - J.K Rowlings",
        "Song of Fire and Ice - George R.R Martin",
    ],

    books: [
        {
            name: 'Big Magic',
            image: '../assets/images/big-magic.png',
            available: true,
            author: ["Elizabeth Gilbert"],
            year: 2014,
            genre: ["Business", "Entrepreneurship"],
            labels: ["Creative", "Self-help"],
            ratings: 4.0,
            borrowed: 31,
            likes: 29,
            featured: true
        },
        {
            name: 'Effective Python',
            image: '../assets/images/effective-python.png',
            available: true,
            author: ["Diomidis Spinellis"],
            year: null,
            genre: ["Motivational"],
            labels: ["Creative", "Self-help"],
            ratings: 4.0,
            borrowed: 31,
            likes: 29,
            featured: true
        },
        {
            name: 'Built To Last',
            image: '../assets/images/built-to-last.png',
            available: false,
            author: ["Jim Collins", "Jerry I. Porras"],
            year: 2001,
            genre: ["Business", "Entrepreneurship"],
            labels: ["Creative", "Self-help"],
            ratings: 4.0,
            borrowed: 31,
            likes: 29,
            featured: true
        },
        {
            name: 'The Lean Startup',
            image: '../assets/images/the-lean-startup.png',
            available: true,
            author: ["Eric Reis"],
            year: 2005,
            genre: ["Motivational"],
            labels: ["Creative", "Self-help"],
            ratings: 4.0,
            borrowed: 31,
            likes: 29,
            featured: true
        },
        {
            name: 'The Effective Engineer',
            image: '../assets/images/the-effective-engineer.png',
            available: true,
            author: ["Edmond Lau"],
            year: 2009,
            genre: ["Motivational"],
            labels: ["Creative", "Self-help"],
            ratings: 4.0,
            borrowed: 31,
            likes: 29,
            featured: true
        },
        {
            name: 'Big Magic',
            image: '../assets/images/big-magic.png',
            available: true,
            author: ["Elizabeth Gilbert"],
            year: 2014,
            genre: ["Business", "Entrepreneurship"],
            labels: ["Creative", "Self-help"],
            ratings: 4.0,
            borrowed: 31,
            likes: 29,
            featured: true
        },
        {
            name: 'Effective Python',
            image: '../assets/images/effective-python.png',
            available: true,
            author: ["Diomidis Spinellis"],
            year: null,
            genre: ["Motivational"],
            labels: ["Creative", "Self-help"],
            ratings: 4.0,
            borrowed: 31,
            likes: 29,
            featured: true
        },
        {
            name: 'Built To Last',
            image: '../assets/images/built-to-last.png',
            available: false,
            author: ["Jim Collins", "Jerry I. Porras"],
            year: 2001,
            genre: ["Business", "Entrepreneurship"],
            labels: ["Creative", "Self-help"],
            ratings: 4.0,
            borrowed: 31,
            likes: 29,
            featured: true
        },
        {
            name: 'The Lean Startup',
            image: '../assets/images/the-lean-startup.png',
            available: true,
            author: ["Eric Reis"],
            year: 2005,
            genre: ["Motivational"],
            labels: ["Creative", "Self-help"],
            ratings: 4.0,
            borrowed: 31,
            likes: 29,
            featured: true
        },
        {
            name: 'The Effective Engineer',
            image: '../assets/images/the-effective-engineer.png',
            available: true,
            author: ["Edmond Lau"],
            year: 2009,
            genre: ["Motivational"],
            labels: ["Creative", "Self-help"],
            ratings: 4.0,
            borrowed: 31,
            likes: 29,
            featured: true
        },
        {
            name: 'Big Magic',
            image: '../assets/images/big-magic.png',
            available: true,
            author: ["Elizabeth Gilbert"],
            year: 2014,
            genre: ["Business", "Entrepreneurship"],
            labels: ["Creative", "Self-help"],
            ratings: 4.0,
            borrowed: 31,
            likes: 29,
            featured: false
        },
        {
            name: 'Effective Python',
            image: '../assets/images/effective-python.png',
            available: true,
            author: ["Diomidis Spinellis"],
            year: null,
            genre: ["Motivational"],
            labels: ["Creative", "Self-help"],
            ratings: 4.0,
            borrowed: 31,
            likes: 29,
            featured: false
        },
        {
            name: 'Built To Last',
            image: '../assets/images/built-to-last.png',
            available: false,
            author: ["Jim Collins", "Jerry I. Porras"],
            year: 2001,
            genre: ["Business", "Entrepreneurship"],
            labels: ["Creative", "Self-help"],
            ratings: 4.0,
            borrowed: 31,
            likes: 29,
            featured: false
        }
    ]
}